# Generated by Django 2.0.3 on 2018-04-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeathLang',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
