# Generated by Django 2.0.3 on 2018-04-19 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langlist',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='语言')),
            ],
        ),
        migrations.CreateModel(
            name='LangText',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('text', models.TextField()),
                ('fors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lang.Langlist')),
            ],
        ),
        migrations.AlterField(
            model_name='deathlang',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='说的话'),
        ),
    ]
